---
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3004:3000"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_CQhz4yuvfUn5@ep-tiny-snow-a8gw7f0b-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      DATABASE_TYPE: postgresql
      APP_SECRET: 747db80fef94d2d565ac51e01caeaa6f07419e41520a0a513ce745d8675a2b1a
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:
